Rba/update board
lukasbals/scraty-mobile pull request #32
Opened 2020-05-12 17:54 UTC by JamieBookstore

2020-05-12 18:25 UTC, BakaBoing approved these changes

2020-05-13 05:47 UTC, BakaBoing requested changes
Lukas wanted to talk about some modifications

2020-05-13 12:52 UTC, lukasbals approved these changes

2020-05-13 12:53 UTC, lukasbals commented
> Lukas wanted to talk about some modifications

@BakaBoing The modifications I requested are addressed. After you reviewed and approved, the PR could be merged.

2020-05-13 13:09 UTC, BakaBoing approved these changes

2020-05-13 13:23 UTC, merged